import { Form } from '@remix-run/react';
import { useState } from 'react';
import VerificationInput from 'react-verification-input';
import { Button } from '../shared';

export const FormSwitcher = ({ actionData, transition }) => {
  const [activeForm, setActiveForm] = useState(0);

  return (
    <div>
      <h2 className="text-2xl  mb-5">Second Factor authentication</h2>
      <>
        {activeForm === 0 && (
          <Form method="post">
            <h3 className="text-xl mb-3 ">Authenticator app</h3>
            <p>Use the code that is generated by your authenticator app</p>
            <div className="max-w-xs mt-5 mb-10 ">
              <label
                htmlFor="authenticationCode"
                className="block text-sm  text-gray-700 mb-5"
              >
                Passcode
              </label>
              <VerificationInput
                autoFocus
                placeholder=" "
                removeDefaultStyles
                classNames={{
                  container: 'container',
                  character: 'character',
                  characterInactive: 'character--inactive',
                  characterSelected: 'character--selected',
                }}
                inputProps={{
                  name: 'authenticationCode',
                }}
              />
            </div>
            <input
              type="hidden"
              name="authenticationChallengeId"
              value={actionData?.totpChallengeId}
            />
            <input type="hidden" name="userId" value={actionData?.userId} />
            {actionData?.errors?.authCode && (
              <div className="pt-1 my-4 text-red-700" id="password-error">
                {actionData.errors.authCode}
              </div>
            )}
            <Button
              name="_action"
              value="verify"
              isLoading={
                transition.state === 'submitting' &&
                transition.submission.formData.get('_action') === 'verify'
              }
              type="submit"
            >
              Verify
            </Button>
            <button
              className="block text-gray-700  my-5 underline"
              onClick={() => setActiveForm(1)}
            >
              Use SMS
            </button>
          </Form>
        )}
      </>
      <>
        {activeForm === 1 && (
          <div>
            <h3 className="text-xl mb-3 ">Text message</h3>
            <p>
              Use the code that is sent to your registered phone number
            </p>{' '}
            <Form method="post">
              <input
                type="hidden"
                name="smsFactorId"
                value={actionData?.smsFactorId}
              />
              <Button
                name="_action"
                value="SMS"
                type="submit"
                isLoading={
                  transition.state === 'submitting' &&
                  transition.submission.formData.get('_action') === 'SMS'
                }
              >
                Send authentication code
              </Button>
            </Form>
            <Form method="post">
              <div className="max-w-xs mt-5 mb-10">
                <label
                  htmlFor="email"
                  className="block text-sm  text-gray-700 mb-5"
                >
                  Passcode
                </label>
                <VerificationInput
                  autoFocus
                  placeholder=" "
                  removeDefaultStyles
                  classNames={{
                    container: 'container',
                    character: 'character',
                    characterInactive: 'character--inactive',
                    characterSelected: 'character--selected',
                  }}
                  inputProps={{
                    name: 'authenticationCode',
                  }}
                />
              </div>
              <input type="hidden" name="userId" value={actionData?.userId} />
              <input
                type="hidden"
                name="authenticationChallengeId"
                value={actionData?.smsChallengeId}
              />
              <Button
                name="_action"
                value="verify"
                type="submit"
                isLoading={
                  transition.state === 'submitting' &&
                  transition.submission.formData.get('_action') === 'verify'
                }
              >
                Verify
              </Button>
              <button
                className="block text-gray-700  my-5 underline"
                onClick={() => setActiveForm(0)}
              >
                Use TOTP
              </button>
            </Form>
          </div>
        )}
      </>
    </div>
  );
};
