import { Form } from '@remix-run/react';
import VerificationInput from 'react-verification-input';
import { Button } from '../shared';

export const TOTPForm = ({ actionData, transition }) => {
  return (
    <Form method="post">
      <h3 className="text-xl mb-3 ">Authenticator app</h3>
      <p>Use the code that is generated by your authenticator app</p>{' '}
      <div className="max-w-xs mt-5 mb-10">
        <label
          htmlFor="authenticationCode"
          className="block text-sm  text-gray-700 mb-5"
        >
          Passcode
        </label>
        <VerificationInput
          autoFocus
          placeholder=" "
          removeDefaultStyles
          classNames={{
            container: 'container',
            character: 'character',
            characterInactive: 'character--inactive',
            characterSelected: 'character--selected',
          }}
          inputProps={{
            name: 'authenticationCode',
            id: 'authenticationCode',
          }}
        />
      </div>
      <input
        type="hidden"
        name="authenticationChallengeId"
        value={actionData?.totpChallengeId}
      />
      <input type="hidden" name="userId" value={actionData?.userId} />
      {actionData?.errors?.authCode && (
        <div className="pt-1 my-4 text-red-700" id="password-error">
          {actionData.errors.authCode}
        </div>
      )}
      <Button
        isLoading={
          transition.state === 'submitting' &&
          transition.submission.formData.get('_action') === 'verify'
        }
        name="_action"
        value="verify"
        type="submit"
      >
        Verify
      </Button>
    </Form>
  );
};
