import { Form, useActionData, useTransition } from '@remix-run/react';
import { Button } from '../shared';
import { VerificationInput } from './verification-input';

export const TOTPForm = () => {
  const actionData = useActionData();
  const transition = useTransition();

  return (
    <Form method="post">
      <h3 className="text-xl mb-3 ">Authenticator app</h3>
      <p>Use the code that is generated by your authenticator app</p>{' '}
      <div className="mt-5 mb-10">
        <VerificationInput />
      </div>
      <input
        type="hidden"
        name="authenticationChallengeId"
        value={actionData?.totpChallengeId}
      />
      <input type="hidden" name="userId" value={actionData?.userId} />
      {actionData?.errors?.authCode && (
        <div className="pt-1 my-4 text-red-700" id="password-error">
          {actionData.errors.authCode}
        </div>
      )}
      <Button
        isLoading={
          transition.state === 'submitting' &&
          transition.submission.formData.get('_action') === 'verify'
        }
        name="_action"
        value="verify"
        type="submit"
      >
        Verify
      </Button>
    </Form>
  );
};
