import { Form } from '@remix-run/react';
import VerificationInput from 'react-verification-input';
import { Loader } from '../shared/loader';

export const TOTPForm = ({ actionData, transition }) => {
  return (
    <Form method="post">
      <h3 className="text-xl mb-3 font-medium">Authenticator app</h3>
      <p>Use the code that is generated by your authenticator app</p>{' '}
      <div className="max-w-xs mt-5 mb-10 ">
        <label
          htmlFor="authenticationCode"
          className="block text-sm font-medium text-gray-700 mb-5"
        >
          Passcode
        </label>
        <VerificationInput
          autoFocus
          placeholder=" "
          removeDefaultStyles
          classNames={{
            container: 'container',
            character: 'character',
            characterInactive: 'character--inactive',
            characterSelected: 'character--selected',
          }}
          inputProps={{
            name: 'authenticationCode',
            id: 'authenticationCode',
          }}
        />
      </div>
      <input
        type="hidden"
        name="authenticationChallengeId"
        value={actionData?.totpChallengeId}
      />
      <input type="hidden" name="userId" value={actionData?.userId} />
      {actionData?.errors?.authCode && (
        <div className="pt-1 my-4 text-red-700" id="password-error">
          {actionData.errors.authCode}
        </div>
      )}
      <button
        className="inline-flex items-center px-4 py-3 border border-transparent shadow-sm text-sm leading-4 font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"
        name="_action"
        value="verify"
        type="submit"
      >
        Verify{' '}
        {transition.state === 'submitting' &&
          transition.submission.formData.get('_action') === 'verify' && (
            <Loader width={4} height={4} />
          )}
      </button>
    </Form>
  );
};
